# Generated by Django 2.1.5 on 2019-01-13 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoseassociation',
            name='first_end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_end', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoseassociation',
            name='second_end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_end', to=settings.AUTH_USER_MODEL),
        ),
    ]
