# Generated by Django 2.1.5 on 2019-01-13 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0002_auto_20190113_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoseassociation',
            name='first_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_end', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hoseassociation',
            name='second_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_end', to=settings.AUTH_USER_MODEL),
        ),
    ]
