# Generated by Django 2.1.5 on 2019-01-19 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0004_hoseassociation_time_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosecontent',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
