# Generated by Django 2.1.5 on 2019-01-19 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0006_associationdemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationdemand',
            name='caduce_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 13, 38, 32, 778281, tzinfo=utc)),
        ),
    ]
