# Generated by Django 2.1.5 on 2019-01-19 22:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0007_auto_20190119_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosecontent',
            name='uploaded_content',
            field=models.FileField(default=b'a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosecontent',
            name='uploader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associationdemand',
            name='caduce_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 22, 1, 44, 286554, tzinfo=utc)),
        ),
    ]
