# Generated by Django 2.1.5 on 2019-01-22 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0008_auto_20190119_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationdemand',
            name='caduce_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 22, 21, 47, 80349, tzinfo=utc)),
        ),
    ]
