# Generated by Django 2.1.5 on 2019-01-25 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hose_usage', '0009_auto_20190122_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationdemand',
            name='caduce_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 0, 23, 11, 958706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='associationdemand',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_origin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associationdemand',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_origin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hosecontent',
            name='hose_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hose_origin', to='hose_usage.HoseAssociation'),
        ),
        migrations.AlterField(
            model_name='hosecontent',
            name='uploader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_origin', to=settings.AUTH_USER_MODEL),
        ),
    ]
